config/routes.rb
Filetunnel::Application.routes.draw do
 

 
  get "password_resets/new"

  mount Resque::Server, :at => "/resque"  

  resources :s3_uploads
  resources :password_resets
  
  get "pages/pricing"
  get "pages/account"
  get "pages/about"
  get "pages/test"
  get "pages/undefined"
  get "pages/tos"
  get "pages/privacy"
  get "pages/contact_us"
  get "pages/vendors"
  get "pages/tour"
  get "pages/features"


  get "sessions/new"

  get "users/new"

  resources :stuffs do
    member do
     get 'download'
   end
  end
  resources :containers do
    member do
      get 'download_all'
      get 'remove'
      get 'remove_folder'
      get 'download_fake'
    end
  end


  get "show_newtransfer" => "containers#show_newtransfer"
  get "partial_update" => "containers#partial_update"
  get "show_container" => "containers#show_container"  
  get "new_transfer" => "containers#new_transfer"
  get "send_notification" => "containers#send_notification"
  

  resources :json
  get "priviledge" => "json#user_info"
  get "storage" => "json#storage"
  get "password_match" => "json#password_match"
  get "compression_check" => "json#before_download_check"

  get "test" => "containers#test"

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  get "sign_up_free" => "users#new_free", :as=>"sign_up_free"
  root :to => "containers#new"
  
  
  resources :users do
    member do 
       put 'update_password'
       put 'update_email'
       put 'update_notifications'
       put 'upgrade'
       get 'confirm'
    end
  end

  resources :sessions
  resources :email_supports
  

  

  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id(.:format)))'

end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
	 def create
	  user = User.find_by_email(params[:email])
	  user.send_password_reset if user
	  redirect_to root_url, :notice => "Email sent with password reset instructions."
	end

	def edit
	  @user = User.find_by_password_reset_token!(params[:id])
	end

	def update
	  @user = User.find_by_password_reset_token!(params[:id])
	  if @user.password_reset_sent_at < 2.hours.ago
	    redirect_to new_password_reset_path, :alert => "Password reset has expired."
	  elsif @user.update_attributes(params[:user])
	    redirect_to root_url, :notice => "Password has been reset!"
	  else
	    render :edit
	  end
	end
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/views/password_resets/edit.html.erb
<div class="custom-form">

<div id="single_action_form">




<%= form_for @user, :url => password_reset_path(params[:id]), :html=>{:class=>"form-stacked"}  do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="clearfix">
  <label for="xlInput3">Password</label>
    <%= f.password_field :password %>
  </div>
  <div class="clearfix">
  <label for="xlInput3">Password Confirmation</label>
    <%= f.password_field :password_confirmation %>
  </div>
              <div style="margin-top:15px;text-align:left">

<button class="btn primary " type="submit">Update Password</button>
</div>

<% end %>

</div>


</div>

app/views/password_resets/new.html.erb
<div class="custom-form">

<div id="single_action_form">

<%= form_tag password_resets_path, :method => :post, :class=>"form-stacked" do %>
	 <h4 style="margin-bottom:10px;">Forgot your password?
     </h4>

     <p>
		Enter your email to reset your password.
     </p>            


    <div class="clearfix">
    <%= text_field_tag :email, params[:email] %>
  	</div>
  <%= submit_tag "Reset Password", :class=>"btn primary" %>
<% end %>
</div>


</div>






<script type="text/javascript" charset="utf-8">


   $(function () {
     $(".secondary-nav").hide();
    });

</script>