config/routes.rb
Filetunnel::Application.routes.draw do
 

 
  get "password_resets/new"

  mount Resque::Server, :at => "/resque"  

  resources :s3_uploads
  resources :password_resets
  
  get "pages/pricing"
  get "pages/account"
  get "pages/about"
  get "pages/test"
  get "pages/undefined"
  get "pages/tos"
  get "pages/privacy"
  get "pages/contact_us"
  get "pages/vendors"
  get "pages/tour"
  get "pages/features"


  get "sessions/new"

  get "users/new"

  resources :stuffs do
    member do
     get 'download'
   end
  end
  resources :containers do
    member do
      get 'download_all'
      get 'remove'
      get 'remove_folder'
      get 'download_fake'
    end
  end


  get "show_newtransfer" => "containers#show_newtransfer"
  get "partial_update" => "containers#partial_update"
  get "show_container" => "containers#show_container"  
  get "new_transfer" => "containers#new_transfer"
  get "send_notification" => "containers#send_notification"
  

  resources :json
  get "priviledge" => "json#user_info"
  get "storage" => "json#storage"
  get "password_match" => "json#password_match"
  get "compression_check" => "json#before_download_check"

  get "test" => "containers#test"

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  get "sign_up_free" => "users#new_free", :as=>"sign_up_free"
  root :to => "containers#new"
  
  
  resources :users do
    member do 
       put 'update_password'
       put 'update_email'
       put 'update_notifications'
       put 'upgrade'
       get 'confirm'
    end
  end

  resources :sessions
  resources :email_supports
  

  

  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id(.:format)))'

end

app/views/notifier/hacker_download_alert.text.erb
This ip: <%= @ip %> is potentially exploiting the system by downloading the same file for more than 10 times


Object Id: <%= @object_id %>

Today's download: <%= @download_today %>

Total download: <%= @download_total %>

app/views/notifier/hacker_upload_alert.text.erb
This ip: <%= @ip %> is potentially exploiting the system by uploading more than 10 GB of files

Today's upload: <%= @upload_today %>

Total upload: <%= @upload_total %>

app/views/notifier/password_reset.text.erb
To reset your password, click the URL below.

<%= edit_password_reset_url(@user.password_reset_token, :host=>"http://share42.herokuapp.com/") %>

If you did not request your password to be reset, just ignore this email and your password will continue to stay the same.

Thanks!

app/views/notifier/plan_support.text.erb
<%= @sender %> wants to know:
<%= @message %>

app/views/notifier/send_invoice.text.erb
Hello <%= @user.email %>,

We’re glad that you’ve chosen 42Share. We hope you have a lot of success – and fun – with it.

Date: <%= Time.zone.now.to_date %>
Invoice period: <%= Time.zone.now.to_date %> - <%= Time.zone.now.to_date + 30.days %>
Customer: <%= @user.email %>
Plan: <% if @user.priviledge == "3" %>Personal<% else %>Premium<% end %>

Your 1 month subscription will renew on  <%= Time.zone.now.to_date + 30.days %>. Your plan continues to cost $(US) <%if @user.priviledge == "3" %>$10 <% else %>$20 <% end %>a month. You can cancel anytime up to the end of the current subscription period. If you cancel before <%= Time.zone.now.to_date + 15.days %>, we will refund you the money for your purchase.

If you have any questions about the invoice, you can reach us via email at support@42share.com.

Please take a look at the user terms. You will find more information below in this email.


Best, 
-The 42Share Team

+++ User Terms +++
Statement of Terms and Conditions:

The user is entitled to withdraw their expression of will to conclude the contract within a time limit of two weeks without giving reasons. The time limit starts on the day after the contract is concluded, i.e. on the day after receipt of the acceptance statement by 42Zen and after receipt of this right of withdrawal instruction in written form. Withdrawal must be declared in written form (e.g. letter, fax, email) to 42Zen. To observe the time limit, it is sufficient to dispatch the declaration of withdrawal in time.
The right of withdrawal ceases to exist at the time 42Zen starts providing the service before the end of the time limit for withdrawal with the user's express consent or if the user itself has initiated the start of the service.
In the event of a valid withdrawal, 42Zen will repay any usage fees already paid by the user.

app/views/notifier/valid_email_confirmation.text.erb
Thanks for signing up with 42share!

The user account with the email address <%= @user.email %> is ready to go. 
With this action you confirm your email address and activate your account on 42Share.

<%= confirm_user_url(@user.confirmation_code,:host=>"www.42share.com") %>

We're really excited to have you on board. We built 42share as an easier way to share. 

Also, do you have ideas or questions? We'd love to hear from you. Just send email to feedback@42share.com. We'd love to hear from you.


Best,
-The 42Share Team