config/routes.rb
Filetunnel::Application.routes.draw do
 

 
  get "password_resets/new"

  mount Resque::Server, :at => "/resque"  

  resources :s3_uploads
  resources :password_resets
  
  get "pages/pricing"
  get "pages/account"
  get "pages/about"
  get "pages/test"
  get "pages/undefined"
  get "pages/tos"
  get "pages/privacy"
  get "pages/contact_us"
  get "pages/vendors"
  get "pages/tour"
  get "pages/features"


  get "sessions/new"

  get "users/new"

  resources :stuffs do
    member do
     get 'download'
   end
  end
  resources :containers do
    member do
      get 'download_all'
      get 'remove'
      get 'remove_folder'
      get 'download_fake'
    end
  end


  get "show_newtransfer" => "containers#show_newtransfer"
  get "partial_update" => "containers#partial_update"
  get "show_container" => "containers#show_container"  
  get "new_transfer" => "containers#new_transfer"
  get "send_notification" => "containers#send_notification"
  

  resources :json
  get "priviledge" => "json#user_info"
  get "storage" => "json#storage"
  get "password_match" => "json#password_match"
  get "compression_check" => "json#before_download_check"

  get "test" => "containers#test"

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  get "sign_up_free" => "users#new_free", :as=>"sign_up_free"
  root :to => "containers#new"
  
  
  resources :users do
    member do 
       put 'update_password'
       put 'update_email'
       put 'update_notifications'
       put 'upgrade'
       get 'confirm'
    end
  end

  resources :sessions
  resources :email_supports
  

  

  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id(.:format)))'

end

app/views/pages/about.html.erb
<style type="text/css" media="screen">

html, body {
background: #C0DEED;
}

.footer{
	margin-top:0px;
}

p{
	padding-bottom: 10px;
font-size: 14px;
line-height: 22px !important;
color: #333 !important;
width: 80%;


}


</style>



<section id="less" style="padding:10px 20px 20px 20px">


<div class="about-heading">
<h3>About</h3>
</div>

<div class="row show-grid">
    <div class="span3">
<ul class="nav pills stacked" style="width: 100%;">
        <li class="active"><a href="#">About 42Share</a></li>
        <li><a href="/pages/contact_us">Contact us</a></li>
        <li><a href="/pages/vendors">Technology Vendors</a></li>
      </ul>

    </div>
    <div class="span11">
    	<h1 style="color: #404040;
font-family: arial,sans-serif;
font-weight: 200;
font-size: 25px;">42Share is the best way to share your large files with your friends, family, colleagues, and clients.
 </h1>

<h2>42</h2>
<p>Answer to the Ultimate Question of Life, the Universe, and Everything</p>


<h2>Why 42share?</h2>


<p>
Sending large files to others can be an extremely frustrating experience. You have probably tried USB drive, email or traditional online sharing sites to send your files, but you never liked them due to a variety of issues such as low capacity, poor security and bad user experience. 42Share will solve your problem once and for all.
<br>

<br>
42Share focuses on providing an easy-to-use and secure sharing service to our users. No installation/registration is required. To share files, simply go to our front page and upload your files; your friends will then receive a link pointing to these files via an email notification. Download & Upload as much as you want and there is absolutely no restriction on the bandwidth you can use. 
<br>
<br>
<strong>Our mission is to make file sharing easier. </strong>
    </div>


</section>

app/views/pages/account.html.erb
<script type="text/javascript" src="https://js.stripe.com/v1/"></script>
<script type="text/javascript">


$(function(){
	$('#refund').popover();
});

</script>


 <%= render :partial =>"/containers/header" %>

<div class="stats" style="display:block" >


            <ul>

                <li><a href="#" class="count" style="padding-left:0px"><%= return_available_space(current_user) %></a><br><span>Availabe/Total space</span></li>
                <li><a href="#" class="count" ><%= @containers.count %></a><br><span>Folders/Transfers</span></li>
                
                <li><a href="#" class="count" title=""><%= number_to_human_size(current_user.storage) %></a><br><span>Space used</span></li>
                 <li><a href="#" class="count" title=""><%= @downloads %></a><br><span>Total Downloads</span></li>

                <li style="width:120px;"><a href="#" class="count"><%= return_plans(current_user) %></a><span>My Plan</span></li>

            </ul>
</div>



	<nav class="sidebar">
			<ul class="sidebar_tab" data-tabs="sidebar_tab">
				<li class="active"><a href="#plans">Plans</a></li>
				<li class=""><a href="#billing_history">Payment History</a></li>						
				<li class=""><a href="#change_password">Change Password</a></li>			
				<li class=""><a href="#change_email">Change Email</a></li>			
				
			</ul>
	</nav>


<div class="tab-content">



<% if current_user.priviledge=="1" %>
	<div class="active" id="plans">
	<table class="plan_table">
		
		<tbody>
			<tr>
				
				<th>
					Plan	
				</th>
				<th>
					Storage	
				</th>
				<th>
					Max transfer size
				</th>
				<th>
					Expiration
				</th>
				<th>
					Action
				</th>
			</tr>


			<tr>
				<td>
					Premium ($20/month)
				</td>
				<td>
					1000GB
				</td>
				<td>
					2GB
				</td>					
				<td>
					Never
				</td>
				<td>
							<a href="#" class="minibutton premium_upgrade" style="height:19px;text-decoration:none;padding-top:0px;">Upgrade</a>
				</td>
			</tr>
			<tr>
				<td>
					Personal ($10/month)
				</td>
				<td>
					100GB
				</td>
				<td>
					2GB
				</td>					
				<td>
					Never
				</td>
				<td>
							<a href="#" class="minibutton personal_upgrade" style="height:19px;text-decoration:none;padding-top:0px;">Upgrade</a>
				</td>
			</tr>
			
			<tr>
				<td>
					Free
				</td>
				<td>
					10GB
				</td>
				<td>
					2GB
				</td>					
				<td>
					30 Days
				</td>
				<td>
							<p style="color:#d8d8d8d;">Your plan</p>
				</td>
			</tr>

		</tbody>
	</table>


	</div>
<% elsif current_user.priviledge=="2" %>


<% elsif current_user.priviledge=="3" %>
<div class="active" id="plans">
	<table class="plan_table">
		
		<tbody>
			<tr>
				
				<th>
					Plan	
				</th>
				<th>
					Storage	
				</th>

				<th>
					Max transfer size
				</th>
					<th>
					Expiration
				</th>

				<th>
					Action
				</th>
			</tr>

			<tr>
				<td>
					Premium ($20/month)
				</td>
				<td>
					1000GB
				</td>
				<td>
					2GB
				</td>					
				<td>
					Never
				</td>
				<td>
							<a href="#" class="minibutton premium_switch" style="height:19px;text-decoration:none;padding-top:0px;">Upgrade</a>
				</td>
			</tr>
			<tr>
				<td>
					Personal ($10/month)
				</td>
				<td>
					100GB
				</td>
				<td>
					2GB
				</td>					
				<td>
					Never
				</td>
				<td>
							<p style="color:#d8d8d8d;">Your plan</p>
				</td>
			</tr>

			<tr>
				<td>
					Free
				</td>
				<td>
					10GB
				</td>
				<td>
					2GB
				</td>					
				<td>
					30 Days
				</td>
				<td>
				</td>
			</tr>

		</tbody>
	</table>


	</div>










<% elsif current_user.priviledge=="4" %>
<div class="active" id="plans">
	<table class="plan_table">
		
		<tbody>
			<tr>
				
				<th>
					Plan	
				</th>
				<th>
					Storage	
				</th>

				<th>
					Max transfer size
				</th>
				<th>
					Expiration
				</th>
				<th>
					Action
				</th>
			</tr>

		
			<tr>
				<td>
					Premium ($10/month)
				</td>
				<td>
					1000GB
				</td>
				<td>
					2GB
				</td>					
				<td>
					Never
				</td>
				<td>
							<p style="color:#d8d8d8d;">Your plan</p>
				</td>
			</tr>
			<tr>
				<td>
					Personal ($5/month)
				</td>
				<td>
					100GB
				</td>
				<td>
					2GB
				</td>					
				<td>
					Never
				</td>
				<td>
							<a href="#" class="minibutton personal_switch" style="height:19px;text-decoration:none;padding-top:0px;">Switch</a>
				</td>
			</tr>

			<tr>
				<td>
					Free
				</td>
				<td>
					10GB
				</td>
				<td>
					2GB
				</td>					
				<td>
					30 Days
				</td>
				<td>
				</td>
			</tr>

		</tbody>
	</table>


	</div>
	

<% end %>

	<div id="billing_history">



		
		<div class="credit-card">
			<div>
			<h3>Past Payments<span><a href="#" id="refund" rel="popover" data-content="You can simply cancel your membership by email at any time by writing to support@42share.com" data-original-title="Refund">Refund</a></span>
</h3>
			</div>

		</div>


		<% if current_user.customer_id.nil? %>
				<p>No payment record yet</p>

		<% else %>
		<table>
			<tbody>


				<tr>
					<th width="75%">
						Amount
					</th>
					<th width="25%">
						Date
					</th>
				</tr>


				<% for p in @payments %>

				<tr>
					<td>
						$<%= ((p.amount.to_f)/100).round(2) %>
					</td>
					<td>
						<%= Time.at(p.created) %>	
					</td>
				</tr>
				<% end %>




			</tbody>
		</table>
		<% end %>






	</div>

	<div id="change_password">
		
	<%= form_for current_user, :url=>update_password_user_path(current_user), :remote=>true do |f| %>
		<h3 style="color:#gray;">
		Change Password
		</h3>		

	  <br>

      <div >
       <input class="span3" id="old_password" name="old_password" size="5" type="password" placeholder="Current password" >
      </div>
	  <br>

      <div > 
       <input class="span3" id="new_password" name="new_password" size="5" type="password" placeholder="New password" >
      </div>

      <div style="margin-top:5px;">
    	<%= submit_tag "Update password", :class=>"btn medium", :style=>"margin-top:15px;" %>

       </div>
    <% end %>


	</div>

	<div id="change_email">
	<%= form_for current_user, :url=>update_email_user_path(current_user), :remote=>true do |f| %>
	<h3 style="color:#gray;">
		Change Email
	</h3>		

	  <br>
	  <p>This will change your sign in and where notification emails are sent to.<p>

      <div > 
       <input class="span3" id="new_email" name="new_email" size="5" value=<%= current_user.email %> >
      </div>

      <div style="margin-top:5px;">
    	<%= submit_tag "Update email", :class=>"btn medium", :style=>"margin-top:15px;" %>

       </div>
    <% end %>	

	</div>

	<div id="notifications">
	<%= form_for current_user, :url=>update_notifications_user_path(current_user), :remote=>true do |f| %>

	<h3 style="color:#gray;margin-left:3px;" >
		Notifications
	</h3>	
            <label id="optionsRadio">Download notification:</label>
            <div class="input" style="margin-left:140px">
              <ul class="inputs-list">
                
   


                <li>
          			<label>
                    	<%= f.check_box :limitnotif %>
                    	<span>Remind me when the file reaches the download limit</span>
                	</label>
              	</li>
              </ul>
            </div>

            <div style="margin-top:5px;">
    			<%= submit_tag "Update setting", :class=>"btn medium", :style=>"margin-top:15px;margin-left:140px;" %>
       		</div>


          
    <% end %>
	</div>


</div>






  </section>
  </section>

<div id="modal-from-dom1" class="modal hide fade in">
            <div class="modal-header">
              <a href="#" class="close">×</a>
              <h3>Credit Card Information</h3>
            </div>
            <div class="modal-body">
		  <p>We'll immediately switch your account to the <span class="plan_show"></span>plan. To verify your identiy, please fill in your credit card information below (there is no additional cost). The cost will be adjusted at the end of the month (?).
		  <br></p>
 <div class="separate"></div>



	<%= form_for current_user, :url=>upgrade_user_path(current_user), :remote=>true, :html=>{:class=>'payment-form-switch'} do |f| %>



				<br>
				<br>


     		    <input name="plan" class="plan" type="hidden" value=""/>

	            <div class="clearfix">
	              <label for="xlInput3">Card Number</label>
	              <div class="input">
	                <input type="text" size="20" autocomplete="off" class="card-number-switch xlarge span5" id="xlInput3" />
	               </div>
	            </div>
	             <div class="clearfix">
	              <label for="xlInput3">CVC</label>
	              <div class="input">
	                <input type="text" size="4" autocomplete="off" class="card-cvc-switch xlarge span2" id="xlInput3"/>
	            </div>
	            </div>

	             <div class="clearfix">
	              <label for="xlInput3">Expiration</label>
	              <div class="input">
	                
	                <input type="text" size="2" class="card-expiry-month-switch span2" placeholder="MM"/>
	                <span> / </span>
	                <input type="text" size="4" class="card-expiry-year-switch span3" placeholder="YYYY"/>
	             </div>
	            </div>

	            <div class="clearfix" style="margin-bottom:0px;">
		            <label for="xlInput3" style="color:#999">We accept</label>
		            <div class="input">
		            	<ul class="cards">
		            		<li>
		            			<span class="visa card">Visa</span>
		            		</li>
		            		<li>
		            			<span class="american_express card">Express</span>
		            		</li>
		            		<li>
		            			<span class="master card">Master</span>
		            		</li>
		            		<li>
		            			<span class="discover card">Discover</span>
		            		</li>
		            		<li>
		            			<span class="jcb card">Jcb</span>
		            		</li>
		            	</ul>
		            </div>
	             </div>


<% end %>
			<div class="separate"></div>
			<div style="width:95%;padding:0 100px;margin-top:20px;">
				<p>Please review the terms of service, and privacy policy.</p>
			</div>
   	          

            </div>




            <div class="modal-footer">
              <a href="#" class="btn secondary" onClick="$('.payment-form-switch').submit()">Switch Plan</a>
            </div>
</div>





<div id="modal-from-dom" class="modal hide fade in">
            <div class="modal-header">
              <a href="#" class="close">×</a>
              <h3>Credit Card Information</h3>
            </div>
            <div class="modal-body">
            <p>Thank you for becoming a paying customer! Once we successfully charge your credit card, we'll immediately upgrade your account to the 
            <span class="plan_show"></span>plan.
            <br>

              </p>

            
	            <div class="separate"></div>





	<%= form_for current_user, :url=>upgrade_user_path(current_user), :remote=>true, :html=>{:class=>'payment-form'} do |f| %>



				<br>
				<br>


     		    <input name="plan" class="plan" type="hidden" value=""/>

	            <div class="clearfix">
	              <label for="xlInput3">Card Number</label>
	              <div class="input">
	                <input type="text" size="20" autocomplete="off" class="card-number xlarge span5" id="xlInput3" />
	               </div>
	            </div>
	             <div class="clearfix">
	              <label for="xlInput3">CVC</label>
	              <div class="input">
	                <input type="text" size="4" autocomplete="off" class="card-cvc xlarge span2" id="xlInput3"/>
	            </div>
	            </div>

	             <div class="clearfix">
	              <label for="xlInput3">Expiration</label>
	              <div class="input">
	                
	                <input type="text" size="2" class="card-expiry-month span2" placeholder="MM"/>
	                <span> / </span>
	                <input type="text" size="4" class="card-expiry-year span3" placeholder="YYYY"/>
	             </div>
	            </div>

	            <div class="clearfix" style="margin-bottom:0px;">
		            <label for="xlInput3" style="color:#999">We accept</label>
		            <div class="input">
		            	<ul class="cards">
		            		<li>
		            			<span class="visa card">Visa</span>
		            		</li>
		            		<li>
		            			<span class="american_express card">Express</span>
		            		</li>
		            		<li>
		            			<span class="master card">Master</span>
		            		</li>
		            		<li>
		            			<span class="discover card">Discover</span>
		            		</li>
		            		<li>
		            			<span class="jcb card">Jcb</span>
		            		</li>
		            	</ul>
		            </div>
	             </div>


<% end %>
			<div class="separate"></div>
			<div style="width:95%;padding:0 15px;margin-top:20px;">
				<p>Please review the terms of service, and privacy policy. 14-Day Money Back Guarantee</p>
			</div>
   	          

            </div>




            <div class="modal-footer">
              <a href="#" class="btn secondary" onClick="$('.payment-form').submit()">Process Credit Card</a>
            </div>
</div>


<script type="text/javascript" charset="utf-8">


   $(function () {
      $(".class").find('> .active').removeClass('active');
      $("#account").addClass('active');
            $("#newtransfer a").css("padding-left","0px");

    });

</script>
 

app/views/pages/contact_us.html.erb
<style type="text/css" media="screen">

html, body {
background: #C0DEED;
}

.footer{
	margin-top:0px;
}

p{
	padding-bottom: 10px;
font-size: 16px;
line-height: 22px !important;
color: #333 !important;
width: 80%;


}


</style>



<section id="less" style="padding:10px 20px 20px 20px">


<div class="about-heading">
<h3>Contact</h3>
</div>

<div class="row show-grid">
    <div class="span3">
<ul class="nav pills stacked" style="width: 100%;">
        <li><a href="/pages/about">About 42Share</a></li>
        <li class="active"><a href="#">Contact us</a></li>
        <li><a href="/pages/vendors">Technology Vendors</a></li>
      </ul>

    </div>
    <div class="span13">
    	<h1 style="color: #404040;
font-family: arial,sans-serif;
font-weight: 200;
font-size: 25px;">Contact Us</h1>

<h3>support@42share.com <small>(for support related issues)</small></h3>
<h3>feedback@42share.com <small>(for suggestions, feedback and comments)</small></h3>
<h3>business@42share.com <small>(for business and press)</small></h3>

    </div>


</section>

app/views/pages/pricing.html.erb
<style type="text/css" media="screen">

.qa p{
color: #454545;
font-size: 15px;
font-weight: normal;
line-height: 20px;
margin-bottom: 10px;
font-family: "Droid Sans","Helvetica Neue",Helvetica,Arial,sans-serif;
}

h4{
	line-height:22px;


}


</style>

<div style="background: #F0F0F0 url('/assets/bg.png') repeat fixed;
border-top: 3px solid #EBEBEB;
border-bottom: 1px solid #E1E1E1;
margin-bottom: 20px;
padding: 30px 0 31px;text-align:center;
width:1600px;margin-left:-300px;

">

      <div class="container ac">
<h1>Choose a Plan | 14-Day Money Back Guarantee</h1>
<h2 style="font-size:20px;color:#777">Send, Store and Share Your Files Anytime, From Anywhere</h2>
      </div>
 </div>


<div class="well" style="margin:auto;margin-bottom:20px;">




<div id="pricingTable">

	<div class="wrap">
		<div class="column-row">
			<div style="">
			
		



					
			<div class="column" id="planBasic">
				<div class="header">
					<h2>Premium</h2>
					<h3>$20/month</h3>
				</div>
				<ul>
					<li>1000 GB</li>
					<li>2 GB Max</li>
					<li>Forever</li>
					<li><img src="/assets/check.png"></li>
					<li><img src="/assets/check.png"></li>
					<li><img src="/assets/check.png"></li>
					<li><img src="/assets/check.png"></li>
					<li><img src="/assets/check.png"></li>
					<li><img src="/assets/check.png"></li>
					<li><img src="/assets/check.png"></li>
					<li><img src="/assets/check.png"></li>
					<li><img src="/assets/check.png"></li>

				</ul>
				<p>
					<a class="blue-sub" href="/sign_up?plan=premium">Free Trial</a>
				</p>
			</div>
		
			<div class="column" id="planBasic">
				<div class="header">
					<h2>Personal</h2>
					<h3>$10/month</h3>
				</div>
				<ul>
					<li>100 GB</li>
					<li>2 GB Max</li>
					<li>Forever</li>
					<li><img src="/assets/check.png"></li>
					<li><img src="/assets/check.png"></li>
					<li><img src="/assets/check.png"></li>
					<li><img src="/assets/check.png"></li>
					<li><img src="/assets/check.png"></li>
					<li><img src="/assets/check.png"></li>
					<li><img src="/assets/check.png"></li>
					<li><img src="/assets/check.png"></li>
					<li></li>


				</ul>
				<p>
					<a class="blue-sub" href="/sign_up?plan=personal">Free Trial</a>
				</p>
			</div>


		
		
		
			<div class="column" id="planPersonal">
				<div class="header">
					<h2 style="margin-left:-7px">Free</h2>
					<h3 style="margin-left:-7px">Free!</h3>
				</div>
				<ul>
					<li>10 GB</li>
					<li>2 GB Max</li>
					<li>Limited</li>
					<li><img src="/assets/check.png"></li>
					<li><img src="/assets/check.png"></li>
					<li><img src="/assets/check.png"></li>	
					<li><img src="/assets/check.png"></li>			
					<li><img src="/assets/check.png"></li>
					<li><img src="/assets/check.png"></li>
					<li><img src="/assets/check.png"></li>

					<li></li>
					<li></li>

				</ul>
				
				<p>
					<a class="blue-sub" href="/sign_up_free">Try It</a>
				</p>
			</div>


			<div class="column" id="planHolder">
		
				<div style="height:94px;">
			



				</div>

				<ul>
					<li>Online storage</li>
					<li>Max transfer size</li>
					<li>Long term storage</li>
					<li>File sharing links</li>
					<li>Unlimited speed</li>
					<li>SSL secure transmissions</li>
					<li>Download entire folders</li>
					<li>Password protected sharing</li>
					<li>Download notification</li>
					<li>Unlimited downloads</li>
					<li>Priority email support</li>
					<li>Ad-free</li>


				</ul>
			
			</div>
		



				



		</div>
	</div>
</div>
</div>





        <div class="row">
<!--
 		<div class="span8">
              <div style="text-align:center;padding-top:30px;">
              <p>
                <a class="btn huge success" href="/sign_up_free" style="width:50%;" title="Register for Fleetio Fleet Management System">
                  <strong>
					Sign Up for Free
		          </strong>
                  <br>
                </a>
              
           		<p>
                Larger plans are also available.
                <a href="/pages/contact_us" title="Contact us">
				Contact us
	            </a>
	            for more info.
              </p>
              </p>

              </div>
              
         
          </div>
-->
         
      </div>






<div class="row">

	<div id="question_head">

	</div>

       <div id="question_form">
          <h4>Confused about which plan to choose?</h4>
          <p>
          	Let us know what you need and we will help you out.
          </p>
          <div style="margin-bottom:15px"></div>
          <h4>Your email address</h4>
<%= form_tag email_supports_path, :method => :post, :class=>"form-stacked",:style=>"padding-left:0px;padding-top:5px;padding-right:20px",:remote=>true do %>
     
          <input type="text" name="sender" class="input-xlarge" style="width:460px">

         <div style="margin-bottom:15px"></div>


          <textarea class="xxlarge" name="message"  spellcheck="false" style="width:460px;height:200px;" ></textarea>


          <div class="form_action">
<button class="btn" type="submit">Send message</button>

          </div>



<% end %>


    </div>

   <div id="question_content"> 
          <h4>Are there any upfront fees?</h4>
          <p>
            No. There are no upfront fees at all to begin using 42Share. You can sign up now and begin
            using it today without even opening your wallet.
          </p>
      
  
   <h4>What web browsers work with 42Share?</h4>
          <p>
            We support Internet Explorer 7 and higher, Firefox 3 and higher, Safari 4 and higher,
            Chrome 4 and higher.
          </p>

 <h4>What are my payment options?</h4>
          <p>
            We accept Visa, MasterCard, Discover and American Express through our online payment system.We do not accept PayPal. 
          </p>

     <h4>How does the 14-day money back work</h4>
          <p>
           If you decide to cancel your subscription within 14 days of signing up you will instantly get your refund. Refunds can not be issued after your initial 14 day trial and we don’t prorate for partial months.
          </p>
    
       <h4>Can I change plans at any time?</h4>
          <p>
           Yep. Simply click on the “Account” tab on your dashboard and you’ll see your options.
          </p>
  <h4>Do I have to sign a long term contract?</h4>
          <p>
          No. There are no long term contracts or commitments on your part. You simply pay month-to-month. If you cancel, you’ll be billed for the current month, but you won’t be billed again.         
          </p>
       
         </div>

</div>

</div>

app/views/pages/tour.html.erb
<style type="text/css" media="screen">

html, body {
background: #CED1D4;
}

.footer{
	margin-top:0px;
}

p{
	padding-bottom: 10px;
font-size: 14px;
line-height: 22px !important;
color: #333 !important;
width: 80%;


}


</style>


<div style="margin-bottom:500px;"></div>

app/views/pages/vendors.html.erb
<style type="text/css" media="screen">

html, body {
background: #C0DEED;
}

.footer{
	margin-top:0px;
}

p{
	padding-bottom: 10px;
font-size: 14px;
line-height: 22px !important;
color: #333 !important;
width: 80%;


}


</style>



<section id="less" style="padding:10px 20px 20px 20px">


<div class="about-heading">
<h3>Technology</h3>
</div>

<div class="row show-grid">
    <div class="span3">
<ul class="nav pills stacked" style="width: 100%;">
        <li><a href="/pages/about">About 42Share</a></li>
        <li><a href="/pages/contact_us">Contact us</a></li>
        <li class="active"><a href="#">Technology Vendors</a></li>
      </ul>

    </div>
    <div class="span13">
    	<h1 style="color: #404040;
font-family: arial,sans-serif;
font-weight: 200;
font-size: 25px;">We team up with the following partners to power 42Share</h1>


<ul class="partner-list">

    <li>
        <img border="0" alt="aws" src="/assets/aws_logo.gif">
    </li>

    <li>
        <img border="0" alt="sendgrid" src="/assets/sendgrid_logo.png">
    </li>

    <li>
        <img border="0" alt="cogent" src="/assets/cogent.jpg">
    </li>

    <li>
        <img border="0" alt="comcast" src="/assets/comcast.jpg">        
    </li>

    <li>
        <img border="0" alt="redhat" src="/assets/redhat-logo1.jpg">
    </li>

    <li>
        <img border="0" alt="solaris" src="/assets/solaris_logo.png">
    </li>

    <li>
        <img border="0" alt="mysql" src="/assets/mysql-logo.jpg">        
    </li>

    <li>
        <img border="0" alt="oralogo" src="/assets/oralogo-small.gif">
    </li>

    <li>
        <img border="0" alt="apache" src="/assets/apache_software_foundation_logo_3074.gif">
    </li>

    <li>    
         <img border="0" alt="microsoft" src="/assets/microsoft-logo.jpg">       
    </li>

    <li>
         <img border="0" alt="akamai" src="/assets/akamai.gif">       
    </li>

    <li>
         <img border="0" alt="heroku" src="/assets/heroku.jpg">       
    </li>





</ul>









    </div>


</section>