config/routes.rb
Filetunnel::Application.routes.draw do
 

 
  get "password_resets/new"

  mount Resque::Server, :at => "/resque"  

  resources :s3_uploads
  resources :password_resets
  
  get "pages/pricing"
  get "pages/account"
  get "pages/about"
  get "pages/test"
  get "pages/undefined"
  get "pages/tos"
  get "pages/privacy"
  get "pages/contact_us"
  get "pages/vendors"
  get "pages/tour"
  get "pages/features"


  get "sessions/new"

  get "users/new"

  resources :stuffs do
    member do
     get 'download'
   end
  end
  resources :containers do
    member do
      get 'download_all'
      get 'remove'
      get 'remove_folder'
      get 'download_fake'
    end
  end


  get "show_newtransfer" => "containers#show_newtransfer"
  get "partial_update" => "containers#partial_update"
  get "show_container" => "containers#show_container"  
  get "new_transfer" => "containers#new_transfer"
  get "send_notification" => "containers#send_notification"
  

  resources :json
  get "priviledge" => "json#user_info"
  get "storage" => "json#storage"
  get "password_match" => "json#password_match"
  get "compression_check" => "json#before_download_check"

  get "test" => "containers#test"

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  get "sign_up_free" => "users#new_free", :as=>"sign_up_free"
  root :to => "containers#new"
  
  
  resources :users do
    member do 
       put 'update_password'
       put 'update_email'
       put 'update_notifications'
       put 'upgrade'
       get 'confirm'
    end
  end

  resources :sessions
  resources :email_supports
  

  

  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id(.:format)))'

end

app/views/layouts/_application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Filetunnel</title>



<script id="template-upload" type="text/x-jquery-tmpl">
    <tr class="template-upload{{if error}} ui-state-error{{/if}}">
        <td class="preview"></td>
        <td class="name">${name}</td>
        <td class="size">${sizef}</td>
        {{if error}}
            <td class="error_detail" colspan="2">Error:
                {{if error === 'custom_failure'}}Custom Error Message
                {{else}}${error}
                {{/if}}
            </td>
        {{else}}
            <td class="progress"><div></div></td>
            <td class="start"><button>Start</button></td>
        {{/if}}
        <td class="cancel"><button>Cancel</button></td>
    </tr>
</script>
<script id="template-download" type="text/x-jquery-tmpl">
    <tr class="template-download{{if error}} ui-state-error{{/if}}">

    </tr>
</script>

  	<script src="//ajax.googleapis.com/ajax/libs/jquery/1.6.1/jquery.min.js"></script>
	<script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.8.13/jquery-ui.min.js"></script>
	<script src="//ajax.aspnetcdn.com/ajax/jquery.templates/beta1/jquery.tmpl.min.js"></script>
<script type="text/javascript" src="https://js.stripe.com/v1/"></script>
<script type="text/javascript">
    // this identifies your website in the createToken call below
    Stripe.setPublishableKey('pk_8QSFtQZHXA1V6vYgFixNDaVt6le5p');
     
  function stripeResponseHandler(status, response) {
                if (response.error) {
                    // re-enable the submit button
                    $('.submit-button').removeAttr("disabled");
                    // show the errors on the form
                    $(".payment-errors").html(response.error.message);
                } else {
                    var form$ = $(".payment-form");
                    // token contains id, last4, and card type
                    var token = response['id'];
                    // insert the token into the form so it gets submitted to the server
                    form$.append("<input type='hidden' name='stripeToken' value='" + token + "' />");
                    // and submit
                    form$.get(0).submit();
                }
            }

  $(document).ready(function() {
  $(".payment-form").submit(function(event) {
    // disable the submit button to prevent repeated clicks
    $('.submit-button').attr("disabled", "disabled");

    var amount = 1000; //amount you want to charge in cents
    Stripe.createToken({
        number: $('.card-number').val(),
        cvc: $('.card-cvc').val(),
        exp_month: $('.card-expiry-month').val(),
        exp_year: $('.card-expiry-year').val()
    }, amount, stripeResponseHandler);

    // prevent the form from submitting with the default action
    return false;
  });
});
</script>

<%= javascript_include_tag "bootstrap-modal"%>
<%= javascript_include_tag 'humane.min' %>
<%= javascript_include_tag 'jquery.iframe-transport' %>
<%= javascript_include_tag 'jquery.fileupload' %>
<%= javascript_include_tag 'jquery.fileupload-ui' %>
<%= javascript_include_tag 'bootstrap-alerts' %>
<%= javascript_include_tag "jquery.tagsinput.js" %>
<%= javascript_include_tag "bootstrap-dropdown" %>
<%= javascript_include_tag "jquery.fixheadertable.js" %>
<%= javascript_include_tag "bootstrap-tabs" %> 

<%= stylesheet_link_tag 'jquery-ui-1.8.16.custom' %>
<%= stylesheet_link_tag 'jquery.fileupload-ui' %>

  <%= stylesheet_link_tag "application" %>
  <%= stylesheet_link_tag "base" %>
  <%= javascript_include_tag "application" %>	
	

  <%= csrf_meta_tags %>
</head>
<body>
	
	
	
	
	
<div class="topbar">
      <div class="fill">
        <div class="container">
          <a class="brand" href="#">
				<img class="logo" width="14" height="18" title="File Tunnel" src="/assets/img_trans.gif">

42Share</a>
          <ul class="nav">
            <li><a href="#about">Plans & Pricing</a></li>
            <li><a href="#contact">Contact</a></li>
          </ul>
         
         <% if current_user %>

    	<ul class="nav secondary-nav">
            <li class="dropdown">
              <a href="#" class="dropdown-toggle"><%= current_user.email %></a>
              <ul class="dropdown-menu">
                <li><a href="#">Secondary link</a></li>
                <li><a href="#">Something else here</a></li>
                <li class="divider"></li>
                <li><%= link_to "Log out", log_out_path %></li>
              </ul>
            </li>
          </ul>
    		   	
    	
    	<% else %>		
			<%= form_tag sessions_path, :class=>"pull-right" do %>
            	 <%= text_field_tag :email, params[:email], :class=>"input-medium", :placeholder=>"Email", :style=>"border:none" %>
            	 <input id="password" name="password" type="password" class="input-small" placeholder="Password" style="border:none">
            	 <button class="btn" type="submit">Sign in</button>
       		<% end %>
        <% end %>
        
        	
    </div>
  </div>
</div>


 	<br>
 	<br>


<div class="container">
	
	
  		
  		
	<%= yield %>



<script type="text/javascript" charset="utf-8">








$('.recipients').tagsInput({
  'height':'30px',
   'width':'483px',
   'unique':true,
   'defaultText':'Email Address(es)' 
});    
    






    
    
</script>



	</div>
  </div>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

  

  <title>42Share - Simple File Sharing</title>

<link rel="shortcut icon" href="/assets/favicon.ico" type="image/x-icon" />
  <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js
"></script>

<%= javascript_include_tag 'jquery-ui.js' %>


<%= javascript_include_tag "bootstrap-modal.js"%>

<%= javascript_include_tag 'bootstrap-alerts.js' %>
<%= javascript_include_tag "jquery.tagsinput.js" %>
<%= javascript_include_tag "bootstrap-dropdown.js" %>
<%= javascript_include_tag "bootstrap-tooltip.js" %>
<%= javascript_include_tag "bootstrap-popover.js" %>
<%= javascript_include_tag "jquery.fixheadertable.js" %>
<%= javascript_include_tag "bootstrap-tabs.js" %> 
<%= javascript_include_tag "jquery.zclip.min.js" %>
<%= javascript_include_tag "jquery.aw-showcase.js" %>
<%= javascript_include_tag "jquery.jcarousel.min.js" %>
<%= javascript_include_tag "jquery.browser.min.js" %>


<link href='https://fonts.googleapis.com/css?family=Lobster' rel='stylesheet' type='text/css'>

  <script type="text/javascript" src="https://js.stripe.com/v1/"></script>
  <%= javascript_include_tag "application" %> 


  <%= stylesheet_link_tag "application" %>
  <meta name="description" content="42share is a simple file sharing service that lets you send and share your large files, photos, docs, and videos easily. "/>
    <meta name="keywords" content="Online File sharing, send large files, secure file transfer, managed file transfer, file transfer, large email attachment, upload files,share files"/>
    <meta name="robots" content="index,follow" />
    <meta name="title" content="Send Large Files Free, Online File Sharing, Transfer Big Files Free, Managed File Transfer | 42Share" />


  <%= csrf_meta_tags %>

<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-37156559-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>

</head>
<body>
<noscript>
    <div class="error message">
        We're sorry but our site <strong>requires</strong> JavaScript.
    </div>    
</noscript>	

<div id="overlay">
	
<div class="topbar">
      <div class="fill">
        <div class="top_container">
          <a class="brand" href="/" style="text-decoration:none;font-family: 'Lobster', cursive;margin-left:450px;">
42Share</a>
        

    <% if current_user %>
    	<ul class="nav secondary-nav">
            <li style="margin-top: 2px;"><a href="/"><i class="icon-home icon-white"></i> Home</a></li>
            <li class="dropdown" style="margin-top: 2px;">
              <a href="#" class="dropdown-toggle"><i class="icon-user icon-white"></i> Account</a>
              <ul class="dropdown-menu">
                <li><a href="/pages/account">Settings</a></li>
                <li><%= link_to "Sign out", log_out_path %></li>
              </ul>
            </li>
        </ul>
    <% else %>		
      <ul class="nav secondary-nav">
          <li class="dropdown">
              <a href="#" class="signin-toggle"><i class="icon-lock icon-white" style="margin-top:1px;margin-right:4px;"></i>Log in</a>   
          </li>
        </ul>
      <% end %>     	
    </div>
  </div>
</div>


 	<br>
  <br>

<div class="container">		
	<%= yield %>
  <% if !current_user %>
  <div id="sign_in_block_wrapper">
  <div id="sign_in_block">

      <%= form_tag sessions_path, :class=>"form-stacked" do %>
           <fieldset>
            <div class="clearfix">
               <label for="xlInput3">Email</label>
               <%= text_field_tag :email, params[:email] %>
            </div>
            <div class="clearfix">
               <label for="xlInput3">Password</label>
               <input id="password" name="password" type="password">
            </div>

            <div class="clearfix" style="margin-bottom:0px">
            <p style="line-height: 20px;margin-top:5px;">
                               <%= check_box_tag :remember_me, 1, params[:remember_me], :style=>"margin-top:2px" %>
<label for="remember_me" style="vertical-align: middle; cursor: pointer;display:inline-block;margin-top: -7px;margin-left:3px; ">Remember me</label>            
            </p>
            </div>
               <a href="/pages/pricing">Create an account</a>
               <button class="btn" type="submit" style="margin-left:38px">Sign in</button>
            </fieldset>
          <% end %>
    </div>
  </div>

<% end %>
      


<% if current_user %>

<% end %>




<script type="text/javascript" charset="utf-8">

$('.recipients').tagsInput({
  'height':'30px',
   'width':'483px',
   'unique':true,
   'defaultText':'Email Address(es)' 
});    
        
</script>

</div>

  <div class="footer">
      <div style="float:left;margin-left:320px;">
        <ul class="left_nav">
            <li><a href="/pages/about" class="at_footer_about">About</a></li>
            <li><a href="/pages/contact_us" class="at_footer_contact">Contact Us</a></li>
            <li><a href="/pages/tos/" class="at_footer_tos">Terms Of Service</a></li>
            <li><a href="/pages/privacy/" class="at_footer_privacy">Privacy Policy</a></li>

        </ul>
      </div>
      <div style="float:left;">
        <p style="float:left;width: 100%;">© Copyright 2012 42Zen, LLC</p>
      </div>
    </div>

	</div>



</body>
</html>